export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_USER_LIST = "SET_USER_LIST";
export const SET_MODIFY_DONE = "SET_MODIFY_DONE";
export const SET_PROVIDER_DETAILS = "SET_PROVIDER_DETAILS";


